package com.example.temperatureconvertor

import android.os.Bundle
import android.util.Log
//import android.util.Log
import android.widget.Button
import android.widget.EditText
import android.widget.Switch
import android.widget.TextView
import androidx.activity.enableEdgeToEdge
import androidx.appcompat.app.AppCompatActivity
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat

class MainActivity : AppCompatActivity() {
    val TAG = "TempConvert"

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        setContentView(R.layout.activity_main)
        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main)) { v, insets ->
            val systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars())
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom)
            insets
        }
        // end of the autogenerated code
        // creating the variables to interact with our components
        val txt_input = findViewById<EditText>(R.id.txt_input)
        val btn_calculate = findViewById<Button>(R.id.btn_calculate)
        val sw_convert = findViewById<Switch>(R.id.sw_convert)
        val lbl_output = findViewById<TextView>(R.id.lbl_output)
        // declare btn_reset
        val btn_reset = findViewById<Button>(R.id.btn_reset)

        btn_calculate.setOnClickListener {
            // got the user input from the textbox, and converted it to a double
            var temperature : Double = txt_input.text.toString().toDouble()
            // check whether the user has checked the switch
            val is_american : Boolean = sw_convert.isChecked

            if (is_american) {
                // leaves a log message, for us as developers, to see little breadcrumbs as to how the app was running
                Log.d(TAG, "The user is converting from F to C")
                // convert from F to C
                temperature = (temperature - 32) * 5 / 9
                // display the conversion result
                lbl_output.text = temperature.toString() + "C"
                Log.d(TAG, "The result of the conversion was " + temperature.toString())
            } else {
                // converting from C to F
                temperature = (temperature * 9 / 5) + 32
                lbl_output.text = temperature.toString() + "F"
            }
            // end of if statement
        }
        // end of button instructions

        // beginning of reset button code
        btn_reset.setOnClickListener {
            // clear the input
            txt_input.text.clear()
            // clear the output
            lbl_output.text = ""
        }

    }
}