package com.example.attendancecounter

import android.os.Bundle
import android.widget.Button
import android.widget.TextView
import androidx.activity.enableEdgeToEdge
import androidx.appcompat.app.AppCompatActivity
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat

class MainActivity : AppCompatActivity() {
    // setting the initial user count to 0
    var count = 0
    // start of the autogenerated code
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        setContentView(R.layout.activity_main)
        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main)) { v, insets ->
            val systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars())
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom)
            insets
        }
        // end of autogenerated code
        // declare variables to communicate with our layout
        val btn_counter = findViewById<Button>(R.id.btn_count)
        val btn_reset = findViewById<Button>(R.id.btn_reset)
        val lbl_output = findViewById<TextView>(R.id.lbl_output)

        // telling android studio what to do when the user clicks the reset button
        btn_reset.setOnClickListener {
            // clearing the output
            lbl_output.text = ""
            // reset the counter
            count = 0
        }

        // telling android studio what to do when the counter button is pressed
        btn_counter.setOnClickListener {
            // first, make the counter go up by 1
            count++
            // then, display the count in the textview
            lbl_output.text = "Count is: " + count.toString()
        }
    }
}